### ISSUE TITLE
background image not covering screen

### ISSUE THREAD

**Issue by Alexg1021** [geekwise-veronica-chavez/dustybuns#1]
burger background img not covering entire screen. Check section height

**Comment by geekwise-veronica-chavez** [comment]
ok thanks

**Comment by haniali1234** [comment]
Page: home
issue: navbar
photo: 
![screen shot 2016-03-21 at 2 43 11 pm](https://cloud.githubusercontent.com/assets/11038599/13935234/8317b1c8-ef73-11e5-956f-4c1db338855a.png)
