### ISSUE TITLE
home page nav bar

### ISSUE THREAD

**Issue by geekwise-kao-thao** [geekwise-veronica-chavez/dustybuns#10]
page: home page
issue: navbar 
photo:

at width 1267px and around it, this is what's happening when hovering over the menu/locations items in the navbar:

![image](https://cloud.githubusercontent.com/assets/17086853/14051996/163b61da-f284-11e5-865d-f253fd485460.png)

**Comment by geekwise-kao-thao** [comment]
i closed this issue because it seemed like it was taken cared of, but today i checked and it's still there.

**Comment by geekwise-kao-thao** [comment]
i see you media queried it and added dropdown to the navbar instead of correcting the issue.  the original website media queried at a small pixel screen.

**Comment by geekwise-kao-thao** [comment]
at 1272px the issue is still visible

![image](https://cloud.githubusercontent.com/assets/17086853/14217025/bb44956c-f800-11e5-850f-1c64fc6e897b.png)

**Comment by geekwise-veronica-chavez** [comment]
can you review again please thanks

**Comment by geekwise-kao-thao** [comment]
good, it's not breaking like before, but for some reason, when hovering over the menu/location item in the navbar, it's pushing the label in the middle of the image down.  it's not smooth.  please check on that.
