### ISSUE TITLE
fresno bistro

### ISSUE THREAD

**Issue by geekwise-kao-thao** [geekwise-veronica-chavez/dustybuns#11]
page: fresno bistro
issue: menu items have gaps.  please see photo below

photo:

![image](https://cloud.githubusercontent.com/assets/17086853/14057061/8cedc0b0-f2b2-11e5-81b9-6a7f47b2dd26.png)

**Comment by geekwise-veronica-chavez** [comment]
fixed all images should fit within its row... thanks

**Comment by geekwise-kao-thao** [comment]
good job.  the spaces are filled, but the menu items are overlapping.

photo:

![image](https://cloud.githubusercontent.com/assets/17086853/14227496/33de3844-f8b4-11e5-99a9-63f78b4b99f0.png)
