### ISSUE TITLE
issue2

### ISSUE THREAD

**Issue by haniali1234** [geekwise-veronica-chavez/dustybuns#14]
page:Home
issue: email is not linked
photo:
![screen shot 2016-03-29 at 10 54 28 am](https://cloud.githubusercontent.com/assets/11038599/14118111/b85a99a2-f59c-11e5-9af9-ca5973df2019.png)

**Comment by geekwise-veronica-chavez** [comment]
its linked to google mail

**Comment by haniali1234** [comment]
I get this: 
![screen shot 2016-03-29 at 11 40 40 am](https://cloud.githubusercontent.com/assets/11038599/14119461/1bfaacee-f5a3-11e5-9ca1-6b37e74f296e.png)

**Comment by geekwise-veronica-chavez** [comment]
all dusty buns footer are linked... thanks for taking time on this issue

**Comment by haniali1234** [comment]
page: home
issue: Email still not linked.

**Comment by geekwise-veronica-chavez** [comment]
yes its linked to mail!

**Comment by haniali1234** [comment]
page:San Francisco Bistro
issue Not linked
photo:
![screen shot 2016-03-31 at 9 35 37 am](https://cloud.githubusercontent.com/assets/11038599/14183259/1ebf3152-f724-11e5-9614-05ce4d6b7a80.png)

**Comment by geekwise-veronica-chavez** [comment]
done all bistro pages linked

**Comment by geekwise-veronica-chavez** [comment]
review issue and close

**Comment by haniali1234** [comment]
page:Contact us
issue Email is not linked
