### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by haniali1234** [geekwise-veronica-chavez/dustybuns#24]
page:Fresno Bistro
issue: The menu is not in order.  or you missing a meal.
Photo:
![screen shot 2016-03-31 at 9 03 42 am](https://cloud.githubusercontent.com/assets/11038599/14182350/b1cbf476-f71f-11e5-8ce8-e51cebf9bf84.png)

**Comment by geekwise-veronica-chavez** [comment]
done fixed added a height and omitted the prices do to the site update.
