### ISSUE TITLE
footer issue

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/dustybuns#5]
issue: footer
page: global

how you have it:
![screen shot 2016-03-23 at 2 14 07 pm](https://cloud.githubusercontent.com/assets/7436666/14001157/df138dfa-f101-11e5-93fa-4074ac2a6825.png)

how it should be:
![screen shot 2016-03-23 at 2 13 55 pm](https://cloud.githubusercontent.com/assets/7436666/14001169/e6d4c338-f101-11e5-81e2-49c428022e51.png)

option: pull-left the copyright and logo, pull-right the tagline

**Comment by geekwise-veronica-chavez** [comment]
fixed footer
