### ISSUE TITLE
favicon 

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-veronica-chavez/dustybuns#7]
you will need to type in the link below in order to save the favicon to your computer and upload it to your site.

favicon: 
![screen shot 2016-03-24 at 2 08 57 pm](https://cloud.githubusercontent.com/assets/7436666/14031426/08699726-f1ca-11e5-9c7b-c80ef76acbc8.png)

**Comment by geekwise-veronica-chavez** [comment]
issue fixed
