### ISSUE TITLE
home page

### ISSUE THREAD

**Issue by geekwise-kao-thao** [geekwise-veronica-chavez/dustybuns#8]
page: home
issue: navbar
photo:

how yours look (not alight horisontally):

![image](https://cloud.githubusercontent.com/assets/17086853/14046696/4a2b6c2a-f260-11e5-935b-77bc32f4106f.png)

how it should look:  

![image](https://cloud.githubusercontent.com/assets/17086853/14046726/70600aae-f260-11e5-8e31-462d676894e6.png)

**Comment by geekwise-veronica-chavez** [comment]
yeah, thanks i just noticed that
