### ISSUE TITLE
home page

### ISSUE THREAD

**Issue by geekwise-kao-thao** [geekwise-veronica-chavez/dustybuns#9]
page: home page
issue:  board image and mid section images are resizing or looks like they are squeezing themselves when screen gets smaller.

yours at width 1000px

![image](https://cloud.githubusercontent.com/assets/17086853/14050342/76a54a74-f278-11e5-9455-75d0272e21a9.png)

at width 700px

![image](https://cloud.githubusercontent.com/assets/17086853/14050394/d84682c0-f278-11e5-8467-ea7d36d7c042.png)

theirs does not get squeezed

**Comment by geekwise-veronica-chavez** [comment]
changed with to % to adjust as it gets smaller

**Comment by geekwise-kao-thao** [comment]
i am glad we verbally discussed this issue in person during the week.  at this moment, looks like the issue is still there.
